name: Build and Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: [1.22]
        include:
          - os: ubuntu-latest
            GOOS: linux
            GOARCH: amd64
          - os: windows-latest
            GOOS: windows
            GOARCH: amd64
          - os: macos-latest
            GOOS: darwin
            GOARCH: amd64
          - os: ubuntu-latest
            GOOS: linux
            GOARCH: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        env:
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}
        run: |
          go build -o animedrive-dl-${{ matrix.GOOS }}-${{ matrix.GOARCH }} ./main.go

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: animedrive-dl-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
          path: animedrive-dl-${{ matrix.GOOS }}-${{ matrix.GOARCH }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Binaries
        uses: actions/download-artifact@v2
        with:
          name: animedrive-dl-linux-amd64

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./binaries/animedrive-dl-linux-amd64
          asset_name: animedrive-dl-linux-amd64
          asset_content_type: application/octet-stream
